# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.22

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/albefero/qubic-cli-main

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/albefero/qubic-cli-main/build

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# Special rule for the target list_install_components
list_install_components:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Available install components are: \"Unspecified\""
.PHONY : list_install_components

# Special rule for the target list_install_components
list_install_components/fast: list_install_components
.PHONY : list_install_components/fast

# Special rule for the target install
install: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install

# Special rule for the target install
install/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Install the project..."
	/usr/bin/cmake -P cmake_install.cmake
.PHONY : install/fast

# Special rule for the target install/local
install/local: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local

# Special rule for the target install/local
install/local/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing only the local directory..."
	/usr/bin/cmake -DCMAKE_INSTALL_LOCAL_ONLY=1 -P cmake_install.cmake
.PHONY : install/local/fast

# Special rule for the target install/strip
install/strip: preinstall
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip

# Special rule for the target install/strip
install/strip/fast: preinstall/fast
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Installing the project stripped..."
	/usr/bin/cmake -DCMAKE_INSTALL_DO_STRIP=1 -P cmake_install.cmake
.PHONY : install/strip/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/albefero/qubic-cli-main/build/CMakeFiles /home/albefero/qubic-cli-main/build//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/albefero/qubic-cli-main/build/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named qubic-cli

# Build rule for target.
qubic-cli: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 qubic-cli
.PHONY : qubic-cli

# fast build rule for target.
qubic-cli/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/build
.PHONY : qubic-cli/fast

#=============================================================================
# Target rules for targets named fourq-qubic

# Build rule for target.
fourq-qubic: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 fourq-qubic
.PHONY : fourq-qubic

# fast build rule for target.
fourq-qubic/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourq-qubic.dir/build.make CMakeFiles/fourq-qubic.dir/build
.PHONY : fourq-qubic/fast

SCUtils.o: SCUtils.cpp.o
.PHONY : SCUtils.o

# target to build an object file
SCUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/SCUtils.cpp.o
.PHONY : SCUtils.cpp.o

SCUtils.i: SCUtils.cpp.i
.PHONY : SCUtils.i

# target to preprocess a source file
SCUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/SCUtils.cpp.i
.PHONY : SCUtils.cpp.i

SCUtils.s: SCUtils.cpp.s
.PHONY : SCUtils.s

# target to generate assembly for a file
SCUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/SCUtils.cpp.s
.PHONY : SCUtils.cpp.s

assetUtils.o: assetUtils.cpp.o
.PHONY : assetUtils.o

# target to build an object file
assetUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/assetUtils.cpp.o
.PHONY : assetUtils.cpp.o

assetUtils.i: assetUtils.cpp.i
.PHONY : assetUtils.i

# target to preprocess a source file
assetUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/assetUtils.cpp.i
.PHONY : assetUtils.cpp.i

assetUtils.s: assetUtils.cpp.s
.PHONY : assetUtils.s

# target to generate assembly for a file
assetUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/assetUtils.cpp.s
.PHONY : assetUtils.cpp.s

connection.o: connection.cpp.o
.PHONY : connection.o

# target to build an object file
connection.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/connection.cpp.o
.PHONY : connection.cpp.o

connection.i: connection.cpp.i
.PHONY : connection.i

# target to preprocess a source file
connection.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/connection.cpp.i
.PHONY : connection.cpp.i

connection.s: connection.cpp.s
.PHONY : connection.s

# target to generate assembly for a file
connection.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/connection.cpp.s
.PHONY : connection.cpp.s

fileUpload.o: fileUpload.cpp.o
.PHONY : fileUpload.o

# target to build an object file
fileUpload.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/fileUpload.cpp.o
.PHONY : fileUpload.cpp.o

fileUpload.i: fileUpload.cpp.i
.PHONY : fileUpload.i

# target to preprocess a source file
fileUpload.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/fileUpload.cpp.i
.PHONY : fileUpload.cpp.i

fileUpload.s: fileUpload.cpp.s
.PHONY : fileUpload.s

# target to generate assembly for a file
fileUpload.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/fileUpload.cpp.s
.PHONY : fileUpload.cpp.s

fourq-qubic.o: fourq-qubic.cpp.o
.PHONY : fourq-qubic.o

# target to build an object file
fourq-qubic.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourq-qubic.dir/build.make CMakeFiles/fourq-qubic.dir/fourq-qubic.cpp.o
.PHONY : fourq-qubic.cpp.o

fourq-qubic.i: fourq-qubic.cpp.i
.PHONY : fourq-qubic.i

# target to preprocess a source file
fourq-qubic.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourq-qubic.dir/build.make CMakeFiles/fourq-qubic.dir/fourq-qubic.cpp.i
.PHONY : fourq-qubic.cpp.i

fourq-qubic.s: fourq-qubic.cpp.s
.PHONY : fourq-qubic.s

# target to generate assembly for a file
fourq-qubic.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/fourq-qubic.dir/build.make CMakeFiles/fourq-qubic.dir/fourq-qubic.cpp.s
.PHONY : fourq-qubic.cpp.s

keyUtils.o: keyUtils.cpp.o
.PHONY : keyUtils.o

# target to build an object file
keyUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/keyUtils.cpp.o
.PHONY : keyUtils.cpp.o

keyUtils.i: keyUtils.cpp.i
.PHONY : keyUtils.i

# target to preprocess a source file
keyUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/keyUtils.cpp.i
.PHONY : keyUtils.cpp.i

keyUtils.s: keyUtils.cpp.s
.PHONY : keyUtils.s

# target to generate assembly for a file
keyUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/keyUtils.cpp.s
.PHONY : keyUtils.cpp.s

main.o: main.cpp.o
.PHONY : main.o

# target to build an object file
main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/main.cpp.o
.PHONY : main.cpp.o

main.i: main.cpp.i
.PHONY : main.i

# target to preprocess a source file
main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/main.cpp.i
.PHONY : main.cpp.i

main.s: main.cpp.s
.PHONY : main.s

# target to generate assembly for a file
main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/main.cpp.s
.PHONY : main.cpp.s

msvault.o: msvault.cpp.o
.PHONY : msvault.o

# target to build an object file
msvault.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/msvault.cpp.o
.PHONY : msvault.cpp.o

msvault.i: msvault.cpp.i
.PHONY : msvault.i

# target to preprocess a source file
msvault.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/msvault.cpp.i
.PHONY : msvault.cpp.i

msvault.s: msvault.cpp.s
.PHONY : msvault.s

# target to generate assembly for a file
msvault.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/msvault.cpp.s
.PHONY : msvault.cpp.s

nodeUtils.o: nodeUtils.cpp.o
.PHONY : nodeUtils.o

# target to build an object file
nodeUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/nodeUtils.cpp.o
.PHONY : nodeUtils.cpp.o

nodeUtils.i: nodeUtils.cpp.i
.PHONY : nodeUtils.i

# target to preprocess a source file
nodeUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/nodeUtils.cpp.i
.PHONY : nodeUtils.cpp.i

nodeUtils.s: nodeUtils.cpp.s
.PHONY : nodeUtils.s

# target to generate assembly for a file
nodeUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/nodeUtils.cpp.s
.PHONY : nodeUtils.cpp.s

proposal.o: proposal.cpp.o
.PHONY : proposal.o

# target to build an object file
proposal.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/proposal.cpp.o
.PHONY : proposal.cpp.o

proposal.i: proposal.cpp.i
.PHONY : proposal.i

# target to preprocess a source file
proposal.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/proposal.cpp.i
.PHONY : proposal.cpp.i

proposal.s: proposal.cpp.s
.PHONY : proposal.s

# target to generate assembly for a file
proposal.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/proposal.cpp.s
.PHONY : proposal.cpp.s

qearn.o: qearn.cpp.o
.PHONY : qearn.o

# target to build an object file
qearn.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qearn.cpp.o
.PHONY : qearn.cpp.o

qearn.i: qearn.cpp.i
.PHONY : qearn.i

# target to preprocess a source file
qearn.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qearn.cpp.i
.PHONY : qearn.cpp.i

qearn.s: qearn.cpp.s
.PHONY : qearn.s

# target to generate assembly for a file
qearn.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qearn.cpp.s
.PHONY : qearn.cpp.s

quottery.o: quottery.cpp.o
.PHONY : quottery.o

# target to build an object file
quottery.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/quottery.cpp.o
.PHONY : quottery.cpp.o

quottery.i: quottery.cpp.i
.PHONY : quottery.i

# target to preprocess a source file
quottery.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/quottery.cpp.i
.PHONY : quottery.cpp.i

quottery.s: quottery.cpp.s
.PHONY : quottery.s

# target to generate assembly for a file
quottery.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/quottery.cpp.s
.PHONY : quottery.cpp.s

qutil.o: qutil.cpp.o
.PHONY : qutil.o

# target to build an object file
qutil.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qutil.cpp.o
.PHONY : qutil.cpp.o

qutil.i: qutil.cpp.i
.PHONY : qutil.i

# target to preprocess a source file
qutil.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qutil.cpp.i
.PHONY : qutil.cpp.i

qutil.s: qutil.cpp.s
.PHONY : qutil.s

# target to generate assembly for a file
qutil.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qutil.cpp.s
.PHONY : qutil.cpp.s

qvault.o: qvault.cpp.o
.PHONY : qvault.o

# target to build an object file
qvault.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qvault.cpp.o
.PHONY : qvault.cpp.o

qvault.i: qvault.cpp.i
.PHONY : qvault.i

# target to preprocess a source file
qvault.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qvault.cpp.i
.PHONY : qvault.cpp.i

qvault.s: qvault.cpp.s
.PHONY : qvault.s

# target to generate assembly for a file
qvault.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qvault.cpp.s
.PHONY : qvault.cpp.s

qx.o: qx.cpp.o
.PHONY : qx.o

# target to build an object file
qx.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qx.cpp.o
.PHONY : qx.cpp.o

qx.i: qx.cpp.i
.PHONY : qx.i

# target to preprocess a source file
qx.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qx.cpp.i
.PHONY : qx.cpp.i

qx.s: qx.cpp.s
.PHONY : qx.s

# target to generate assembly for a file
qx.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/qx.cpp.s
.PHONY : qx.cpp.s

walletUtils.o: walletUtils.cpp.o
.PHONY : walletUtils.o

# target to build an object file
walletUtils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/walletUtils.cpp.o
.PHONY : walletUtils.cpp.o

walletUtils.i: walletUtils.cpp.i
.PHONY : walletUtils.i

# target to preprocess a source file
walletUtils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/walletUtils.cpp.i
.PHONY : walletUtils.cpp.i

walletUtils.s: walletUtils.cpp.s
.PHONY : walletUtils.s

# target to generate assembly for a file
walletUtils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/qubic-cli.dir/build.make CMakeFiles/qubic-cli.dir/walletUtils.cpp.s
.PHONY : walletUtils.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... install"
	@echo "... install/local"
	@echo "... install/strip"
	@echo "... list_install_components"
	@echo "... rebuild_cache"
	@echo "... fourq-qubic"
	@echo "... qubic-cli"
	@echo "... SCUtils.o"
	@echo "... SCUtils.i"
	@echo "... SCUtils.s"
	@echo "... assetUtils.o"
	@echo "... assetUtils.i"
	@echo "... assetUtils.s"
	@echo "... connection.o"
	@echo "... connection.i"
	@echo "... connection.s"
	@echo "... fileUpload.o"
	@echo "... fileUpload.i"
	@echo "... fileUpload.s"
	@echo "... fourq-qubic.o"
	@echo "... fourq-qubic.i"
	@echo "... fourq-qubic.s"
	@echo "... keyUtils.o"
	@echo "... keyUtils.i"
	@echo "... keyUtils.s"
	@echo "... main.o"
	@echo "... main.i"
	@echo "... main.s"
	@echo "... msvault.o"
	@echo "... msvault.i"
	@echo "... msvault.s"
	@echo "... nodeUtils.o"
	@echo "... nodeUtils.i"
	@echo "... nodeUtils.s"
	@echo "... proposal.o"
	@echo "... proposal.i"
	@echo "... proposal.s"
	@echo "... qearn.o"
	@echo "... qearn.i"
	@echo "... qearn.s"
	@echo "... quottery.o"
	@echo "... quottery.i"
	@echo "... quottery.s"
	@echo "... qutil.o"
	@echo "... qutil.i"
	@echo "... qutil.s"
	@echo "... qvault.o"
	@echo "... qvault.i"
	@echo "... qvault.s"
	@echo "... qx.o"
	@echo "... qx.i"
	@echo "... qx.s"
	@echo "... walletUtils.o"
	@echo "... walletUtils.i"
	@echo "... walletUtils.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

